name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    env:
      TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ vars.GCP_REGION }}
      TF_VAR_zone: ${{ vars.GCP_ZONE }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_alert_email: ${{ vars.GCP_ADMIN_MAIL }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: ./environments/prod

      - name: Remove old Kubernetes resources from state
        shell: powershell
        run: |
          terraform state rm kubernetes_deployment.hr_portal
          $global:LASTEXITCODE = 0
          terraform state rm kubernetes_service.hr_portal_svc
          $global:LASTEXITCODE = 0
        working-directory: ./environments/prod
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./environments/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./environments/prod

      - name: Install GKE Auth Plugin
        shell: powershell
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
        continue-on-error: true

      - name: Deploy HR Portal to GKE
        shell: powershell
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
        run: |
          Write-Host "Koppelen aan het GKE cluster..."
          gcloud container clusters get-credentials innovatech-gke-prod --zone $env:TF_VAR_zone --project $env:TF_VAR_project_id

          Write-Host "Toepassen van het HR Portal manifest..."
          kubectl apply -f k8s/hr-portal.yaml
