name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    env:
      TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ vars.GCP_REGION }}
      TF_VAR_zone: ${{ vars.GCP_ZONE }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_peer_gateway_ip_0: ${{ vars.GCP_PEER_IP_0 }}
      TF_VAR_peer_gateway_ip_1: ${{ vars.GCP_PEER_IP_1 }}
      TF_VAR_vpn_shared_secret: ${{ secrets.VPN_SHARED_SECRET }}
      TF_VAR_alert_email: ${{ vars.GCP_ADMIN_MAIL }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: ./environments/prod

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./environments/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./environments/prod
